### ISSUE TITLE
update libusb support

### ISSUE THREAD

**Issue by artmeln** [micro-manager/mmCoreAndDevices#186]
I’m writing a device adapter that uses libusb as a library. After looking at 3rdpartypublic, it looks like libusb versions utilized by MM device adapters in the past are rather outdated. Would it be possible to add libusb-1.0 to 3rdpartypublic? It is the current platform independent version of the library.

**Comment by marktsuchida** [comment]
I think we can make use of libusb 1.0 without necessarily updating the existing device adapters that need libusb 0.1 (aka libusb-compat). If you contribute a device adapter that uses libusb-1.0, we should be able to add a Windows binary to 3rdpartypublic (and a scripted build for macOS).

Let's not add dependencies until they are actually used, however.

Also, it will be good to make sure that talking directly to libusb is the right thing to do, i.e., that you are not reinventing what USBManager does.

**Comment by artmeln** [comment]
libusb (version 1.0.26) has been made available in 3rdpartypublic
