### ISSUE TITLE
Understanding prior stage adapters

### ISSUE THREAD

**Issue by ianhi** [micro-manager/mmCoreAndDevices#189]
There seem to be two difference folders for prior stages: `Prior` and `Prior Legacy` both of which have comments about proscan in them. Is there an easy way to determine which is being used in my setup?

I'd like to add callbacks to these

**Comment by marktsuchida** [comment]
It should be listed in your hardware configuration file, under `# Devices`, as the third comma-separated item on the line. I'd be surprised if you are using `PriorLegacy`.
