### ISSUE TITLE
path to 3rd party

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/mmCoreAndDevices#219]
Trying to setup the paths for a device adapter, and when I include `$(MM_3RDPARTYPRIVATE)` it resolves to a path with an extra `\` in `VisualStudio\\`. I think this is inherited from a project default so changing it doesn't seem like the right solution. Any ideas what might be going on?

@marktsuchida @nicost 

![Capture](https://user-images.githubusercontent.com/7969470/178043880-77cf55e0-6608-4a5b-badb-495a6a68dc99.PNG)

**Comment by marktsuchida** [comment]
Does it actually affect the build?
Usually `$(MM_3RDPARTYPRIVATE)\path\to\libdir` works in the context you are showing.

**Comment by henrypinkard** [comment]
Whoops, you're right. I guess that was an unrelated error I was seeing. Thanks!
