### ISSUE TITLE
MicroFPGA build

### ISSUE THREAD

**Issue by jdeschamps** [micro-manager/mmCoreAndDevices#292]
Hi!
I noticed that [MicroFPGA](https://github.com/micro-manager/mmCoreAndDevices/tree/main/DeviceAdapters/MicroFPGA) is not shipped with 2.0.0 or the NB. It is not in `micromanager.sln`.

Any specific reason? Should I make a PR to add it to the `.sln`file?

Thanks!

**Comment by marktsuchida** [comment]
I was wondering about that (#207). Please feel free to make a PR.

**Comment by jdeschamps** [comment]
Done https://github.com/micro-manager/mmCoreAndDevices/pull/293!
