### ISSUE TITLE
Point Grey Device Adapter and MM version conflicts

### ISSUE THREAD

**Issue by kmdouglass** [micro-manager/mmCoreAndDevices#363]
Hi everyone,
We're having issues with the Point Grey device adapter in Micro-Manager versions newer than February 2, 2022. On this date, the FlyCap SDK was updated from 2.10.3.266 to 2.13.3.61 as described in #130 . We noticed that the device adapter will not load in these newer MM versions if FlyCap 2.10.3.266 is installed.

So, we tried instead to install FlyCap 2.13.3.61 but now we cannot proceed past the hardware configuration wizard because the device adapter code returns an error if the FlyCap DLL version is not 2.10.3.266 in the `Initialize` method: https://github.com/micro-manager/mmCoreAndDevices/blob/main/DeviceAdapters/PointGrey/PointGrey.cpp#L263-L268

I was wondering whether you can confirm or not that updating the check on the required version of the DLL in `PointGrey.cpp` will fix the issue. I could set up a Windows compilation environment to fix it, but I wanted to run it by someone here first to make sure it's the right fix.

Any ideas? Thanks!

**Comment by marktsuchida** [comment]
Fixed by #364.
