### ISSUE TITLE
Memory access and definition when developing a new camera adapter

### ISSUE THREAD

**Issue by NeversayEverLin** [micro-manager/mmCoreAndDevices#380]
Hi, I am using micro-manager C++ source to develop a camera adapter, which is used for Adimec camera via BitFlow frame grabber. There is one thing I am very confusing when looking through all the demoCam or other adapters, is about the memory access. In most of camera adapter, they usually have their own defined memory and save into their defined memory after capture. In my understanding is that after capture, it is require to do memcpy to copy the camera's own memory to the uManager's device memory, is that correct? To do so, the most straightforward way is to use ImgBuffer which is provided by the uManager source. However, on the other hand, I say lots of camera adapter just define a buffer (such as void* imgBuff_, which has nothing to do with uManager) and then assign the camera acquired buffer to this user-defined imgBuff, and never try to re-assign to ImgBuffer class. If so, how does the uManager get access to those memory (I mean doing so, the uManager has no way to know where to find the right buffer, right?).  

Another thing is about the uManager core function mmcore.getImage(). I am wondering how this function works at the lower level, i.e. how it get access to the camera's captured image? Or do we need to insert all the capture images into the uManager's circular buffer (this is also confusing to me about the circular buffer; how this circular buffer works with camera?)?. Thanks a lot!

**Comment by nicost** [comment]
In Micro-Manager's model, cameras can operate in 2 modes: Snap mode and Sequence (video) mode.  In Snap mode, the code will call the `SnapImage()` function in your device adapter.  The camera is supposed to start the exposure as fast as it can, and to return immediately after the exposure ends (i.e., not wait until the image is transferred into the computer's memory).  This is to ensure correct synchronization with light sources (and shutters).  Userland code then requests the image data using a call to the function `GetImageBuffer()` which returns the data as a `const char*` where the interpretation of that data depends on a number of other functions in the camera API.

Things work differently in sequence mode, which is started with a call to the function `StartSequenceAcquisition(long numImages, double interval_ms, bool stopOnOverflow)` in your adapter.  This function is supposed to start a sequence of images in the camera, and - on a separate thread - start returning images by copying them into the MMCore circular buffer using ` GetCoreCallback()->InsertImage`.  

The code for the DemoCamera device adapter is pretty well annotated, so hopefully you can get clarity by looking at that code with these pointers.
