### ISSUE TITLE
uM2 gamma pixel size doesn't update with Ti2 tube lens

### ISSUE THREAD

**Issue by samjlord** [micro-manager/mmCoreAndDevices#47]
When I change the tube lens on the Ti2, uM2 gamma doesn't update the pixel size, unless I press the "refresh" button. In uM1.4, the pixel size changes instantaneously. When using our old Ti scope with an Arduino- and magnet-based tube lens sensor, the pixel size updates immediately in uM2 gamma. For the Ti2, the tube lens property is not included in the pixel size calibration.

**Comment by nicost** [comment]
This should work now after the Nikon Ti2 adapter updates I did a while ago.  Please re-open if it does not work.
