### ISSUE TITLE
Can’t locate mmgr_dal_NI-DAQmx.dll

### ISSUE THREAD

**Issue by JoeB-NIH** [micro-manager/mmCoreAndDevices#481]
Hi 

@fadero @nicost

we downloaded the latest release of MM v2 and could not find the adapter for NI-DAQmx in the wizard. the associated dll file is not found in the MM folder
![IMG_5272](https://github.com/user-attachments/assets/f50459af-9f16-480c-9cfc-f6640341990f)

**Comment by nicost** [comment]
That is so weird!  I just installed the latest nightly build (20240714), and it is there.  Can you try that one?

![image](https://github.com/user-attachments/assets/fec5f921-4bd5-4ea0-ae5f-0617a8fb8ff4)

**Comment by nicost** [comment]
Oh, I get it.  You downloaded the latest "release".  You always want to download the latest nightly build from https://download.micro-manager.org/nightly/2.0/Windows/.  The latest "release" is about 3 years out of date.  Nightly builds are very stable, and have many features not found in the release.

**Comment by JoeB-NIH** [comment]
hey Nico

I will take a look at this tomorrow

appreciate the quick response

This is Joe Brzostowski btw from the NIH!

cheers

**Comment by JoeB-NIH** [comment]
Nico

I just want to make sure that there isn’t a specific uninstall procedure
for uManager other than deleting the folder (I thought this all we have to
do)

yesterday when working with my IT person (I lost my admin privileges -
getting back hate the gov that way) we ran the the “unins000” but that
didn’t delete the uManager folder

just curious

joe

**Comment by JoeB-NIH** [comment]
Nico

dont bother responding

figured out

the uninstall didn’t work yesterday because uManger was not in Programs
file

long story as to why

joe

**Comment by nicost** [comment]
No worries Joe,

Micro-Manager does not install files outside of the MIcro-Manager folder
where it installs, so you can safely delete it (or rename, or whatever).  I
even often install into the same folder to upgrade to a newer version.
Usually there are no issues (only in rare cases where you also have to
install other files into the Micro-Manager folder to make things work).

Hope they will give you admin privileges again!

Best,


Nico
