### ISSUE TITLE
OpenFlexure throws "Unknown Error in device (1)" 

### ISSUE THREAD

**Issue by beniroquai** [micro-manager/mmCoreAndDevices#494]
When downloading the latest nightly and adding the OpenFlexure device adapter to the configuration I get the following error:

![image](https://github.com/user-attachments/assets/73015bbd-746d-4304-aa96-e888b2fc9af6)

I'm yet relatively new to MicroManager and don't know (yet) how to interpret/resolve this error. Is this a general error or my personal fault? Any chance how to debug it? Thanks! 

CC: @henrypinkard @samdrea

**Comment by samdrea** [comment]
Hi Benedict,

I really should’ve been more specific about the errors I throw, because I’m
not sure how to interpret it either. I will have access to the microscope
this coming weekend, so I will try to debug and make the error messages
more informative then. Sorry about that!

Best,
Samdrea

**Comment by beniroquai** [comment]
No worries at all. Thanks a lot for publishing the sources. I'm starting to learn how it works based on your code :)

**Comment by samdrea** [comment]
Hi Benedict,

I found the error! It seems that when I don't plug in the sangaboard in the
right port and try to go through the hardware configuration wizard,
micromanager will throw errors at me. I had written the device adapter to
send serial commands during the configuration stage, so I think the error
could be from the serial commands not going through. I'm adding some more
lines in my code to warn users of that now, but it probably won't be
integrated for a while. Let me know if plugging the Sangaboard into the
computer before the hardware configuration resolves the issue.

Please don't hesitate to let me know if any other issues arise.

Best,
Samdrea

**Comment by beniroquai** [comment]
Ah, that makes sense. That was my guessing as well after I have read into the code a bit. I think a refined error message may help a bit! Thanks a lot for checking!! :)
I guess we can close this issue then.

**Comment by samdrea** [comment]
Of course! If you find more sketchy parts of the code, feel free to reach
out to ***@***.*** This was the first ever device adapter I
wrote, so there is definitely room for improvement!
