### ISSUE TITLE
Spinnaker device adapter does not work

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/mmCoreAndDevices#64]
The Spinnaker camera device adapter does not work with Spinnaker SDK version 2.3.0.77 or with the latest version of the SDK. The device adapter works well if we compile it with VS2015, SDK v2.3.0.77, and Spinnakerd_v140.lib dependencies. How is the .dll distributed with the MM nightly builds compiled?

**Comment by marktsuchida** [comment]
It is currently built with VS2010. Please see https://micro-manager.org/Spinnaker.

**Comment by ieivanov** [comment]
The device adapter worked with SDK v2.3.0.77 and VS2010 libraries, thanks @marktsuchida!
